package data

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import java.time.LocalDateTime


@Serializable
data class BuyData(
    val itemId: Int,
    val amountBought: Int,
    val pricePerItem: Double,
    // date is automatically generated by psql on insert
    @Contextual val date: LocalDateTime = LocalDateTime.MIN
)
